service: costtracking-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowCredentials: false

functions:
  api:
    handler: dist/serverless.handler
    events:
      - httpApi:
          path: /
          method: ANY
      - httpApi:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000   # You can change the port if needed
    lambdaPort: 3002 # Optional, for lambda invoke endpoint
